#!/bin/bash

# Parameters that can be passed, set to empty by default
INPUT=""
OUTPUT=""
DESC=""

# Help function
usage() {
	printf "%s\n" ""
	printf "%s\n" "Image2HTML"
	printf "%s\n" "Converts an image to an embeded html img tag with base64 encoding."
	printf "%s\n" ""
	printf "%s\n" "Arguments: "
	printf "%-30s" "(-h|--help): " 
	printf "%s\n" "Displays the help page."
	printf "%-30s" "(-i|--input 'file'): "
	printf "%s\n" "The input file, the image to be converted."
	printf "%-30s"  "(-o|--output 'file'): "
	printf "%s\n" "The file to output results to."
	printf "%-30s" "(-d|--description 'desc'): "
	printf "%s\n" "The description of the image, used in html alt attribute."
	printf "%s\n" ""
}

# Function for handling errors when they occur
throw_error() {
	# If there is a message passed, print it, otherwise just print a generic error message
	if [ -z "$1" ]
	then
		printf "%s\n" "An Unknown Error Occured."
	else
		printf "%s\n" "$1"
	fi
	
	# Print usage and exit with an error code of 1
	usage
	exit 1
}

# Collect arguments
while [ "$1" != "" ]; do
	case $1 in
		-h | --help)
			usage
			exit
			;;
		-i | --input)
			shift
			INPUT=$1
			;;
		-o | --output)
			shift
			OUTPUT=$1
			;;
		-d | --description)
			shift
			DESC=$1
			;;
		*)
			throw_error "ERROR: Unknown parameter \"$1\""
			;;
	esac
	shift
done

# If there is no input parameter, print usage and exit
if [ -z "$INPUT" ] 
then
	throw_error "ERROR: No input defined."
fi

# If there is no output parameter, set it to input with .html extension appended 
if [ -z "$OUTPUT" ]
then
	OUTPUT="$INPUT.html"
fi

# Mute standard error for all commands below, since there is already custom error handling below
{

# Let user know we are begining conversion...
printf "%s\n" "Attempting to convert file \"$INPUT\"..."

# Get image data and encode it using base64
IMG_DATA=$(base64 "$INPUT") || throw_error "Input file \"$INPUT\" does not exist."

# Get mime type of the input
MIME_TYPE=$(file -b --mime-type "$INPUT")

# Write image tag to output location using mime type, image data, and description collected earlier.
printf "%s\n" "<img src=\"data:$MIME_TYPE;base64, $IMG_DATA\" alt=\"$DESC\">" > "$OUTPUT" || throw_error "Can't write to \"$OUTPUT\""

# We are finished! Notify the user...
printf "%s\n" "Finished converting, saved to \"$OUTPUT\""

} 2> /dev/null

